### ISSUE TITLE
Make nav elements smaller so more fit in

### ISSUE THREAD

**Issue by IzzySoft** [SansPseudoFix/Oc-old-menu-stylish#1]
First thanks for the userstyle – saves a click on each switch! Still, I'd prefer to have it a little smaller; so for one it's more decent, and with more OCApps active, you don't need to scroll it. Played a little, and these are the additions I came up with:

```
/* additions by Izzy: Make nav elements smaller so more fit in */
#navigation, #apps { width: 70px !important; }
#navigation a { padding: 5px 0 !important; height: 60px !important; width: 60px; }
#navigation a span { font-size: 11px !important; width: 60px; }
#navigation .app-icon { max-width: 20px !important; }
#content-wrapper { padding-left: 70px !important; }
```

I've just added them at the end of the userstyle (to make them easier to distinguish). You might wish to "merge" them with yours, as they duplicate/overwrite some of the definitions (e.g. you already have a block for `#navigation`).

Tested with OC8, works fine :smile_cat:

**Comment by SansPseudoFix** [comment]
Thanks for improvements! I have to confess that I don't use this userstyle, because I made [an apps](https://github.com/SansPseudoFix/Old_menu) to do this (also available in [the market](https://apps.owncloud.com/content/show.php/Old+menu?content=166872)), so this style is not up to date.

But I will check that ASAP :)

**Comment by IzzySoft** [comment]
Yes, I saw that app as well – but prefer the UserStyle (easier to toggle that way) :smiley_cat: But my adjustments might of course be interesting for the app as well, if they feel right to you. So I look forward to your reaction once you've tried them out.

Thanks for the fast feedback!

**Comment by SansPseudoFix** [comment]
Well, I made some improvements for my app on dev branch ([you can see here](https://github.com/SansPseudoFix/Old_menu/blob/dev/css/old_menu.css)). I really think smaller icons are a good idea, but I prefer `%` than `px`.
So icons are now with 11px and `#navigation` is a little bit smaller (7% -> 6%).
I update this style too (and thx you in changelog).

Of course, if you don't like my version, feel free to fork this repo and make your own version ! It's free :)

**Comment by IzzySoft** [comment]
As long as it matches, I don't care whether it's done with px, em, or % :smile: And yes, I know forking is free – if you see my profile and its repositories, you can tell :) In fact I've thought of forking and creating a pull-request – but discarded that idea, already expecting you want to do it differently.

Just tried your new style – wow, you did more than I asked for! So maybe I suppose one more line again:

``` .css
#apps { margin-left:-10px; margin-top: 10px; }
```

Or the equivalent in percent if you prefer. Looks more symmetric – at least to me.

**Comment by SansPseudoFix** [comment]
You're right for margin. I add it. Thanks again :) 

Now, I have to do same with my app.

**Comment by IzzySoft** [comment]
I have to thank you – great job, looks amazing! Glad I was able to contribute to it!
