### ISSUE TITLE
Adjustment for 8.1+

### ISSUE THREAD

**Issue by IzzySoft** [SansPseudoFix/Oc-old-menu-stylish#2]
Slowly catching up (after having ignored updates for too long): For 8.1, the userstyle needed a small adjustment for the `#navigation` element. Just make line 17

```
top:45px; left:0;
```

(i.e. adding the `left:0;`) to get rid of the ugly gray bar on the left of it :) Don't know yet for 8.2 and up. Will let you know when I'm there in case it needs another fix-up. One more:

```
/* Get rid of the up-pointing navigation arrow */
#navigation:after, #expanddiv:after {
  border-width: 0;
  margin-left: 0;
}
```

**Comment by SansPseudoFix** [comment]
Thanks for your contribution! But I no longer maintain this style. I don't use it (it was just for a friend). Feel free to fork it and maintain it, I'll put a link to your repository.

**Comment by IzzySoft** [comment]
Ah, I see. So if you completely stop it: Shall I fork (and leave your repo as "pointer" – as it is linked e.g. from oc apps) – or do you rather wish to transfer it to me entirely? I'm fine with either.

Btw: does the "no longer maintain" also apply to the oc app?

**Comment by SansPseudoFix** [comment]
> Ah, I see. So if you completely stop it: Shall I fork (and leave your repo as "pointer" – as it is linked e.g. from oc apps) – or do you rather wish to transfer it to me entirely? I'm fine with either.

Since they are very few users for this style, and upgrades are not automatics through github, I think a fork is good enough. BTW, maybe consider using [userstyles.org](https://userstyles.org/) (for automatic updates for example).

> Btw: does the "no longer maintain" also apply to the oc app?

Probably, yes. I'm not quite sure right now, but as I don't use this app too, I can't maintain it correctly, and [direct menu](https://apps.owncloud.com/content/show.php/Direct+Menu?content=169148) looks like doing a really great work, so...

**Comment by IzzySoft** [comment]
OK, thanks for the feedback. While I cannot do anything on the oc app, I've just [forked this repo](https://github.com/IzzySoft/Oc-old-menu-stylish) and applied my updates (one more update for 8.2 was required when using the `files_markdown` app). As I already have some styles on USO, I'll see to adding this one as well shortly.

Cannot promise any big news, but certainly will keep the user script working for a while :)

PS: USO still doesn't support refreshing code from Github. So copy-pasting it there would mean maintaining two places. As auto-updates are not possible anyway (due to the URL the user needs to fill in – for which a "text setting" could be used but would then [prevent auto-updates](https://userstyles.org/help/coding#help-style-settings-updating)), I'm not sure if that's really useful. Apart from that, I'd need to specify a license (my default would be CC BY-NC-SA).

Btw: Do you want my changes back to your repo as PR? :)

**Comment by SansPseudoFix** [comment]
Sorry for the delay.

> Apart from that, I'd need to specify a license (my default would be CC BY-NC-SA).

Well, I didn't specify any licence, but it would be CC0. So, do what you want with my code ;)

> Btw: Do you want my changes back to your repo as PR? :)

Nope, it's fine. I linked your repo to my [readme.md](https://github.com/SansPseudoFix/Oc-old-menu-stylish/commit/9782409d27f7b2b246637a19570c351cee0b0f13). Users will be aware.

**Comment by IzzySoft** [comment]
OK, so let's leave it at that (I'll then have to live with the fact that activities on the clone are not counted as activities on Github until "merged upstream"). I'll think about putting it at USO, though due to the manual adjustments needed I'm not sure how useful that is – apart from making it better known, that is. I don't expect that many modifications :)

As you probably no longer update the oc app either, maybe putting a note there as well?

**Comment by IzzySoft** [comment]
**Update:** I've inserted a "generic document scope" which should fit in 99.9% of all installations (`@-moz-document regexp("https?://[^/]+(:[0-9]+)?/owncloud/.*") {`. As this permits installation without adjustments, I've [uploaded it to USO](https://userstyles.org/styles/131444/oc-old-menu-stylish) now. Just in case you want to point there as well.

PS: Some updates have been applied to the script, too :)

**Comment by SansPseudoFix** [comment]
> As this permits installation without adjustments, I've uploaded it to USO now. Just in case you want to point there as well.

[Done](https://github.com/SansPseudoFix/Oc-old-menu-stylish/blob/master/README.md#this-repo-is-outdated-please-use-izzysofts-fork-instead-or-his-userstylesorg-repo) :)

**Comment by IzzySoft** [comment]
Sorry for bringing this up again, but some minor issues I'd like to address:

* **Github:** If somebody searches for it, none of our repos would turn up "recent": yours is outdated, mine just a fork (and thus by default excluded from search results). May I suggest you make me "collaborator" for your repo here, so I continue maintaining it in its original place? All credits stay with you :)
* **[Old_menu app](https://github.com/SansPseudoFix/Old_menu):** there you refer to [Direct Menu](https://apps.owncloud.com/content/show.php/Direct+Menu?content=169148) – which breaks e.g. nextcloud 9 (reported by some users, and I was able to reproduce the issue immediately; worst, with the menu totally gone then, you need to know the exact URL to the app settings in order to disable it again). Maybe you want to point to this userstyle as well from there, for a second alternative?

PS: Script just updated for oc 8.2-9.1, nextcloud support added, "sliding menu" invented, USO-copy updated as well :)
